# Generated by Django 3.1.7 on 2021-03-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.CharField(blank=True, max_length=50, verbose_name='Event id')),
                ('summary', models.CharField(max_length=120, verbose_name='Title')),
                ('organizer', models.CharField(blank=True, max_length=50, verbose_name='Organizer of event ')),
                ('start_time', models.DateTimeField(auto_now=False, verbose_name='Event start time')),
                ('end_time', models.DateTimeField(auto_now=False, verbose_name='Event end time')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
    ]
